FORMAT: 1A
HOST: http://booking-api.windingtree.com/

# Booking API

Hotel Booking API allows hotels upload their inventory and users create bookings.

## Hotels Availability [/search-available-hotels]

### Search for Availability [POST]

Search given area for available hotels.

+ Request (application/json)

        {
            "lat": 0,
            "lng": 0,
            "radius": 10000, # 10km, more range -> more results (paginated)
            "guests_number": 2,
            "amenities": [] # specific needs
        }

+ Response 200 (application/json)

        [
            "http://booking-api.windingtree.com/hotels/7f0ddae0ac541bd1"
        ]

## Hotels Collection [/hotels]

### List All Hotels [GET]

Details for any Hotel object in the database.

+ Response 200 (application/json)

        [
            {
                "resource": "http://booking-api.windingtree.com/hotels/7f0ddae0ac541bd1",
                "name": "Vista del Pinnella Pass",
                "description": "Long text of describing this venue...",
                "created": "2017-04-25T12:56:29.310Z",
                "location": {
                    "lat": 0,
                    "lng": 0
                },
                "address": {
                    "line 1": "979 Forest Drive",
                    "line 2": "",
                    "zip": "22181",
                    "city": "Vienna",
                    "country": "Rwanda"
                },
                "timezone": "CAT", # UTC+02:00
                "rating": 4.8,
                "capacity": 1024,
                "amenities": [],
                "images": []
            }
        ]

## Hotel Invetory Upload [/hotel-inventory]

### Upload New Invetory [POST]

You can upload available rooms of any type for any day
with given capacity and price.

+ Request (application/json)

        {
            "hotel": "http://booking-api.windingtree.com/hotels/7f0ddae0ac541bd1",
            "min_guests": 1,
            "max_guests": 2,
            "room_type": "Double Queen Bed",
            "rooms_available": 10,
            "date": "2017-05-05",
            "price": 120,
            "currency": "USD",
            "amenities": []
        }

+ Response 201 (application/json)

    + Headers

            Location: /upload-inventory/a68da69c5644ec70

    + Body

            {
                "resource": "http://booking-api.windingtree.com/upload-inventory/a68da69c5644ec70",
                "hotel": "http://booking-api.windingtree.com/hotels/7f0ddae0ac541bd1",
                "min_guests": 1,
                "max_guests": 2,
                "room_type": "Double Queen Bed",
                "rooms_available": 10,
                "date": "2017-05-05",
                "price": 120,
                "currency": "USD",
                "amenities": []
            }

## Hotel Room Booking [/hotel-bookings]

### Create Hotel Room Booking [POST]

Booking of a room in one hotel.

+ Request (application/json)

        {
            "hotel": "http://booking-api.windingtree.com/hotels/7f0ddae0ac541bd1",
            "date_from": "2017-05-05",
            "date_till": "2017-05-06",
            "guests": [
                {
                    "name": "Marjorie Muriel Peterson",
                    "email": "marjorie.peterson@windingtree.com",
                    "phone": "+43605456789",
                    "pnr": "", # this is very airline specific, what else do we need to identify person?
                    "note": "i want to stay in this hotel"
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /hotel-bookings/e0af617e28919045

    + Body

            {
                "resource": "http://booking-api.windingtree.com/hotel-bookings/e0af617e28919045",
                "hotel": "http://booking-api.windingtree.com/hotels/7f0ddae0ac541bd1",
                "date_from": "2017-05-05",
                "date_till": "2017-05-06",
                "guests": [
                    {
                        "name": "Marjorie Muriel Peterson",
                        "email": "marjorie.peterson@windingtree.com",
                        "phone": "+43605456789",
                        "pnr": "",
                        "note": "i want to stay in this hotel"
                    }
                ]
            }

